baseURL = "https://mitbitcoinexpo.org/new"
languageCode = "en-us"
title = "MIT Bitcoin Expo 2020"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe= true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

# [[menu.main]]
#     name = "Hackathon"
#     url = "/hackathon"
#     weight = 3

# [[menu.main]]
#     name = "Speakers"
#     url = "/speakers"
#     weight = 4

# [[menu.main]]
#     name = "Sponsors"
#     url = "/sponsors"
#     weight = 5

# [[menu.main]]
#     name = "Committee"
#     url = "/committee"
#     weight = 6

# [[menu.main]]
#     name = "Gallery"
#     url = "/gallery"
#     weight = 7

[[menu.main]]
    name = "Prior Expos"
    url = "https://web.archive.org/web/*/http://mitbitcoinexpo.org/"
    weight = 8

[params]
  google_analytics_id=""
  homepage_button_link = 'https://mit.universitytickets.com'
  homepage_button_text = 'Register Now'
  homepage_button_link2 = '/about'
  homepage_button_text2 = 'About The Expo'
  homepage_intro = ''
  homepage_image = '/images/btc-live.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MIT Bitcoin Expo 2020"
    meta_og_title = "MIT Bitcoin Expo 2020"
    meta_og_type = "website"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
