baseURL = "https://mitbitcoinexpo.org/"
languageCode = "en-us"
title = "MIT Bitcoin Expo 2020"
themesDir = "themes"
theme = "hugo-whisper-theme"

disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Speakers"
    url = "/speakers/"
    weight = 3
    
[[menu.main]]
    name = "Agenda"
    url = "/agenda/"
    weight = 4

[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 5

[[menu.main]]
    name = "Hackathon"
    url = "/hackathon/"
    weight = 6

[[menu.main]]
    name = "Committee"
    url = "/committee/"
    weight = 7

 [[menu.main]]
    name = "WiB Networking"
    url = "https://meetu.ps/e/HK3vZ/JTbkL/a"
    weight = 8

[[menu.main]]
    name = "Prior Expo"
    url = "/flashback_2019/"
    weight = 9

[[menu.main]]
    name = "Register"
    url = "https://www.eventbrite.com/e/mit-bitcoin-expo-2020-tickets-91011105667"
    weight = 10

[params]
  google_analytics_id= "UA-159043754-1"
  homepage_button_link = 'https://eepurl.com/gOVdKb'
  homepage_button_text = 'Join The Mailing List'
  homepage_button_link2 = '/about'
  homepage_button_text2 = 'About The Expo'
  homepage_button_link3 = 'https://www.eventbrite.com/e/mit-bitcoin-expo-2020-tickets-91011105667'
  homepage_button_text3 = 'Register Now'
  homepage_intro = ''
  homepage_image = '/images/btc-live.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MIT Bitcoin Expo 2020"
    meta_og_title = "MIT Bitcoin Expo 2020"
    meta_og_type = "website"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
