baseURL = "https://mitbitcoinexpo.org/"
languageCode = "en-us"
title = "MIT Bitcoin Expo 2021"
themesDir = "themes"
theme = "mit-bitcoin-expo-theme"

disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Speaker Application"
    url = "/app"
    weight = 2

[[menu.main]]
    name = "Prior Expo"
    url = "/flashback_2020/"
    weight = 9

[params]
  google_analytics_id= "UA-159043754-1"
  homepage_button_link = 'https://eepurl.com/gOVdKb'
  homepage_button_text = 'Join The Mailing List'
  homepage_button_link2 = 'https://forms.gle/uzrJSBLetz7co66K7'
  homepage_button_text2 = 'Speaker Application'
  homepage_button_link3 = 'https://forms.gle/JUvaggfVCNS8P54G7'
  homepage_button_text3 = 'Hackathon'
  homepage_button_link4 = '#'
  homepage_button_text4 = 'Become a Sponsor'
  homepage_intro = ''
  homepage_image = '/images/btc-live.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MIT Bitcoin Expo 2021"
    meta_og_title = "MIT Bitcoin Expo 2021"
    meta_og_type = "website"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
